name: Promote Forecast

on:
  workflow_dispatch:    # 👈 habilita "Run workflow" manual en GitHub Actions
  push:                 # 👈 opcional: se dispara también cuando hay push en main
    branches:
      - main

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run forecast promotion
        run: |
          echo "Promoting forecast..."
          python scripts/promote_forecast.py

